apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: cnv-sriov-profile 
spec:
  cpu:
    isolated: "2-19,22-39"
    reserved: "0-1,20-21"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16 
  realTimeKernel:
    enabled: true 
  nodeSelector:
    node-role.kubernetes.io/master: "" 
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
